### ISSUE TITLE
Overzooming Issue 

### ISSUE THREAD

**Issue by millzpaugh** [mapsam/map#2]
This is my favorite zxy map finder, so I'm documenting a small overzooming bug that I found! It appears  xy does not change for zoom levels that require overzooming. 

![overzoom-problems-mapsam](https://user-images.githubusercontent.com/4648295/50855215-19016c80-133c-11e9-8371-6b3cbfdd3615.gif)

**Comment by mapsam** [comment]
Heya @millzpaugh! This is due to https://github.com/mapbox/mapbox-gl-js/issues/5535, unfortunately out of my hands here 😄
