### ISSUE TITLE
Please add more cowbell

### ISSUE THREAD

**Issue by flippmoke** [mapsam/map#3]
as per title

**Comment by mapsam** [comment]
Hey @flippmoke thanks for the issue! I have a few questions.

* do you want to download cowbell from the info panel?
* how much cowbell is enough?
* how are you managing without cowbell currently?

**Comment by flippmoke** [comment]
>do you want to download cowbell from the info panel?

I need more cowbell

>how much cowbell is enough?

You will know when its done.

>how are you managing without cowbell currently?

My current symptoms are hives, a cough, occasionally bursting into tears, and the inability to walk in a straight line.

**Comment by mapsam** [comment]
Please call 911 @flippmoke - they will help with lack of cowbell symptoms. 

In the meantime, I’ll scale out the sites capacity to handle the increased cowbell.
